apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: mlops-poc
  labels:
    name: mlops-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mlops-poc
  template:
    metadata:
      name: mlops-poc
      labels:
        name: mlops-poc
    spec:
      containers:
        - name: mlops-poc
          image: docker.io/devlogic123/image-repo:latest
          command: ["/bin/sh"]
          args: ["-c", "python3 run.py"]
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
   name: mlops-svc
spec:
  type: LoadBalancer
  selector:
    name: mlops-poc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
